

title: <p align="center"> Pooja Pal </p>
logo: thumbnail.png

description:
  <p align="center">
  <a href="https://www.linkedin.com/in/pooja-pal-a6903529/">LinkedIn</a> |
  <a href="https://github.com/ppcoder0204">GitHub</a>
  
  <br>   
 Hi,
 I am a cybersecurity professional with 15 years of IT experience and solving most complex Org level IAM solutions.
  <br>
  </p>



theme: jekyll-theme-minimal